name: para_takip_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # HTTP istekleri için
  http: ^1.1.0

  # State management
  provider: ^6.1.1

  # Local storage (token saklama)
  shared_preferences: ^2.2.2

  # İkonlar
  cupertino_icons: ^1.0.8

  # Number format
  intl: ^0.18.1

  # Grafikler için
  fl_chart: ^0.68.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/panda-normal.png
    - assets/images/panda-hidden.png

